name: Build Capstone ARM64

on:
  push:
    branches:
      - main  # Replace with your branch name
  pull_request:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make

      - name: Build Capstone for ARM64
        run: |
          chmod +x ./build_capstone.sh
          ./build_capstone.sh ARM64

      - name: Archive Capstone Build
        uses: actions/upload-artifact@v2
        with:
          name: capstone-arm64
          path: path/to/your/build_directory  # Replace with actual path to build directory
