name: Build Capstone Static Library

on:
  push:
    branches:
      - main  # 触发分支可以根据需要调整

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS 环境运行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 克隆仓库到工作目录

      - name: Find Capstone.xcodeproj
        run: |
          find . -name "Capstone.xcodeproj"
        id: find_xcodeproj
        continue-on-error: true

      - name: Install Xcode and Command Line Tools
        if: steps.find_xcodeproj.outputs.stdout != ''
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch
          sudo xcodebuild -license accept
          sudo installer -pkg /Applications/Xcode.app/Contents/Resources/Packages/XcodeSystemResources.pkg -target /

      - name: Build Capstone Static Library
        if: steps.find_xcodeproj.outputs.stdout != ''
        run: |
          xcodebuild -project ${{ steps.find_xcodeproj.outputs.stdout }} -target CapstoneStatic -configuration Release clean build
        env:
          XCODE_PROJECT_PATH: ${{ steps.find_xcodeproj.outputs.stdout }}

      - name: Archive artifacts
        if: steps.find_xcodeproj.outputs.stdout != '' && success()
        uses: actions/upload-artifact@v2
        with:
          name: capstone-static-library
          path: ${{ env.XCODE_PROJECT_PATH }}/build/Release/libcapstone.a
