name: Build iOS Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    env:
      PLATFORM: iPhoneOS
      SDK_VERSION: 15.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install CMake
        run: |
          brew install cmake
          cmake --version
      
      - name: Set up environment variables
        run: |
          export SDK_PATH=$(xcrun --sdk $PLATFORM --show-sdk-path)
          export TOOLCHAIN_PATH=$(xcrun --sdk $PLATFORM --find clang)
      
      - name: Create build directory
        run: mkdir -p build_ios
      
      - name: Configure CMake
        run: |
          cd build_ios
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCAPSTONE_BUILD_DIET=OFF \
                -DCAPSTONE_ARM64_SUPPORT=ON \
                -DCAPSTONE_USE_SYSTEMD=OFF \
                -DCAPSTONE_BUILD_TESTS=OFF \
                -DCMAKE_OSX_ARCHITECTURES=arm64 \
                -DCMAKE_OSX_SYSROOT=$SDK_PATH \
                -DCMAKE_C_COMPILER=$TOOLCHAIN_PATH \
                -DCMAKE_CXX_COMPILER=$TOOLCHAIN_PATH \
                ..
      
      - name: Build project
        run: cmake --build . --config Release -- -j8
