name: Build Capstone for ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          brew install cmake
          cmake --version

      - name: Set up Xcode environment
        run: |
          export PLATFORM=iPhoneOS
          export SDK_VERSION=15.0
          export SDK_PATH=$(xcrun --sdk $PLATFORM --show-sdk-path)
          export TOOLCHAIN_PATH=$(xcrun --sdk $PLATFORM --find clang)

      - name: Configure CMake and Build Capstone for iOS
        run: |
          mkdir -p build_ios
          cd build_ios
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCAPSTONE_BUILD_DIET=OFF \
                -DCAPSTONE_ARM64_SUPPORT=ON \
                -DCAPSTONE_USE_SYSTEMD=OFF \
                -DCAPSTONE_BUILD_TESTS=OFF \
                -DCMAKE_OSX_ARCHITECTURES=arm64 \
                -DCMAKE_OSX_SYSROOT=$SDK_PATH \
                -DCMAKE_C_COMPILER=$TOOLCHAIN_PATH \
                -DCMAKE_CXX_COMPILER=$TOOLCHAIN_PATH \
                ..

          cmake --build . --config Release -- -j8

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: capstone-arm64-artifact
          path: build_ios/libcapstone.a
