name: Build Capstone Static Library

on:
  push:
    branches:
      - main  # 触发分支可以根据需要调整

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS 环境运行

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 克隆仓库到工作目录

      - name: Install Xcode
        uses: actions/setup-xcode@v2  # 设置 Xcode 环境

      - name: Build Capstone Static Library
        run: |
          xcodebuild -project Capstone.xcodeproj -target CapstoneStatic -configuration Release clean build
        working-directory: path/to/Capstone.xcodeproj  # 替换成 Capstone.xcodeproj 的路径

      - name: Archive artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: capstone-static-library
          path: path/to/Capstone.xcodeproj/build/Release/libcapstone.a  # 替换成实际生成的 libcapstone.a 路径
